### ISSUE TITLE
Fighter Compendium - Power Attack - Usage incorrect

### ISSUE THREAD

**Issue by cswendrowski** [Mageflame/Toolkit13#93]
In GitLab by @James-Firth on Sep 11, 2020, 21:29

## Summary

(Summarize the bug encountered concisely)

## Steps to reproduce

1. View Fighter Compendium
2. Open Talents
3. View "Power Attack"

## What is the current bug behavior?

**Power Usage** is set to `Other` by default. (Effect lists "Once per battle")

## What is the expected correct behavior?

**Power Usage** should be set to `Once per battle` as per the SRD https://www.13thagesrd.com/classes/fighter

## Relevant logs and/or screenshots

![image](/uploads/044b81518100a26925762e7c676df3e7/image.png)

## Possible fixes (optional, remove this section if unneeded)

Change default value

## Labels (do-not-change)

/cc @asacolips @cswendrowski

**Comment by James-Firth** [comment]
@cswendrowski for future reference do you prefer issues posted on github or gitlab? I used gitlab since that was the link in the module on Foundry

**Comment by cswendrowski** [comment]
Hey there @James-Firth! Sorry for the pings, that was part of the import over from Gitlab. We're not done moving just yet, but this will be the new home, so please create new issues here. Thanks!

**Comment by James-Firth** [comment]
No worries and sounds good!
